name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  #commentato per ora che ho solo errore  <Validation brands> failed:  The repository has not been added as a custom domain to the brands repo (More info: https://hacs.xyz/docs/publish/include#check-brands )
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: integration
          ignore: "brands"

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v2.3.4"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
